# Copyright (C) 2024 officialputuid

name: getgrass-bot

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # 7 PM (WITA)
    - cron: '0 17 * * *' # 1 AM (WITA)

jobs:
  getgrass:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.repository }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup ENV
        run: |
          sudo apt update -y
          sudo apt install -y nodejs npm
          echo "BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ env.REPO_NAME }}" >> $GITHUB_ENV

      - name: Setup Resources
        run: |
          npm install
          echo -e "${{ secrets.UID_LIST }}" > uid.txt
          ${{ secrets.WGET_PROXIES }}
          cat proxy-1.txt proxy-2.txt proxy-3.txt proxy-4.txt >> proxy.txt
          rm -rf proxy-*.txt

      - name: Notify Start
        run: |
          USER_COUNT=$(wc -l < uid.txt | xargs)
          PROXY_COUNT=$(wc -l < proxy.txt | xargs)
          DATE_TIME=$(TZ='Asia/Makassar' date '+%Y-%m-%d %H:%M:%S %Z')
          curl -s -X POST "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ env.CHAT_ID }} \
            -d text="[$DATE_TIME] Workflow ($REPO_NAME) has started. UID: $USER_COUNT and Proxies: $PROXY_COUNT."

      - name: Run getgrass
        continue-on-error: true
        timeout-minutes: 345
        run: npm start

      - name: Notify Completion
        if: always()
        run: |
          DATE_TIME=$(TZ='Asia/Makassar' date '+%Y-%m-%d %H:%M:%S %Z')
          curl -s -X POST "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ env.CHAT_ID }} \
            -d text="[$DATE_TIME] Workflow ($REPO_NAME) has completed."
